pipeline {
        stage('Checkout'){
            parallel {
                stage('Checkout-HelloWorld') {
                    steps{
                        echo 'Removing original source code for internal - /opt/devops/pullrequest/c'
                        sh 'rm -rf /opt/devops/pullrequest/c'
                        ws('/opt/devops/pullrequest/c'){
                            echo "Workspace dir is ${pwd()}"
                            checkout([$class: 'GitSCM', branches: [[name: 'master']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'CleanBeforeCheckout'], [$class: 'PruneStaleBranch'], [$class: 'RelativeTargetDirectory', relativeTargetDir: 'helloworld']], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/art-niu/helloworld.git']]])
                            
                        }
                    }
                }
            }
        }
    agent {
        docker { image 'arthurniu/gcc-ubuntu:1.0' }
    }
    stages {
        stage('Test') {
            steps {
                sh 'gcc -v'
            }
        }
    }
}
