pipeline {
    agent any
    parameters {
        string(defaultValue: 'Branch_HelloWorld_Feature', description: 'Which branch to build?', name: 'BRANCH_NAME')
    }

    stages {
        stage('Checkout'){
            steps{
                        echo 'Removing original source code for internal - /opt/devops/pullrequest/c'
                        sh 'rm -rf /opt/devops/pullrequest/c'
                        ws('/opt/devops/pullrequest/c'){
                            echo "Workspace dir is ${pwd()}"
                            checkout([$class: 'GitSCM', branches: [[name: BRANCH_NAME ]], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'CleanBeforeCheckout'], [$class: 'PruneStaleBranch'], [$class: 'RelativeTargetDirectory', relativeTargetDir: 'helloworld']], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/art-niu/helloworld.git']]])
                            
                        }
           }
        }

        stage('Build') {
            agent {
        	docker { image 'arthurniu/gcc-ubuntu:1.0' }
                args '-v /opt/devops:/opt/devops -w /opt/devops/pullrequest/c'
                reuseNode true
    	    }
            steps {
                sh 'ls /opt/workSpace/HelloWorld/HelloWorld-C/c/helloworld/pullrequest'
            }
        }

        stage('Test') {
            steps {
                sh 'gcc -v'
            }
        }
    }
}
